version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "visit-count"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-847jjvwk5rm0"
s3_prefix = "visit-count"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
